version: '2'
services:
  vs:
    #image: docker.pkg.github.com/5gzorro/mda/vs_testing:latest
    build: ./dummy_vs_connector
    ports:
      - "3700:3700"
    expose:
      - "3700"
    depends_on:
      - mda
    links:
      - "mda"
    networks:
      front:
        ipv4_address: 172.253.1.0
  mda:
    #image: docker.pkg.github.com/5gzorro/mda/mda_testing:latest
    build: ./mda
    ports:
      - "4000:4000"
    expose:
      - "4000"
    environment:
      KAFKA_URL: ${KAFKA_URL}
      OPERATOR_PUBLIC_KEY: ${OPERATOR_PUBLIC_KEY}
      POSTGRES_USER: "postgres"
      POSTGRES_PW: ${POSTGRES_PW}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_DB: "mda_test"
    networks:
      front:
        ipv4_address: 172.253.1.1
  osm:
    #image: docker.pkg.github.com/5gzorro/mda/osm_testing:latest
    build: ./dummy_osm_connector
    ports:
      - "4500:4500"
    expose:
      - "4500"
    depends_on:
      - vs
      - mda
    links:
      - "vs"
      - "mda"
    networks:
      front:
        ipv4_address: 172.253.1.2
networks:
  front:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.253.0.0/16
